# Generated by Django 4.0 on 2021-12-14 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('exhibit_id', models.AutoField(primary_key=True, serialize=False)),
                ('exhibit_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timestamp', models.DateField(auto_now=True)),
                ('featured_date', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(blank=True, default=False)),
                ('revealed', models.BooleanField(blank=True, default=False)),
                ('artist_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='studios.comment')),
            ],
            options={
                'verbose_name_plural': 'Exhibits',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('rotation_id', models.AutoField(primary_key=True, serialize=False)),
                ('delay', models.TimeField()),
                ('current', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exhibit', to='studios.exhibit')),
            ],
            options={
                'verbose_name_plural': 'Rotations',
            },
        ),
        migrations.AddField(
            model_name='exhibit',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='studios.image'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='studios.Tag'),
        ),
    ]
