# Generated by Django 4.0 on 2021-12-14 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='images',
        ),
        migrations.AddField(
            model_name='comment',
            name='exhibit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studios.exhibit'),
        ),
        migrations.AddField(
            model_name='image',
            name='exhibit',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.DO_NOTHING, to='studios.exhibit'),
        ),
    ]
