# Generated by Django 4.0 on 2021-12-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_comment_exhibit_alter_image_options_image_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotation',
            options={'verbose_name_plural': 'Rotations'},
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
