# Generated by Django 4.0 on 2021-12-14 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_remove_exhibit_comments_remove_exhibit_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='exhibit',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pics', to='studios.exhibit'),
        ),
    ]
