# Generated by Django 4.0 on 2021-12-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_alter_image_exhibit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='exhibit',
            new_name='exhibit_name',
        ),
    ]
