# Generated by Django 4.0 on 2021-12-09 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_alter_rotation_options_alter_exhibit_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibit',
            old_name='comment',
            new_name='comments',
        ),
    ]
