# Generated by Django 4.0 on 2021-12-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_rename_comment_exhibit_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
    ]
