# Generated by Django 4.0 on 2021-12-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_rename_exhibit_image_exhibit_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='image_name',
        ),
    ]
