# Generated by Django 4.0 on 2021-12-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_rename_name_image_image_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
    ]
