# Generated by Django 4.0 on 2021-12-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0006_alter_tag_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='name',
        ),
    ]
