# Generated by Django 4.0 on 2021-12-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0006_alter_exhibit_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='images',
            field=models.IntegerField(default=int, null=True),
        ),
    ]
