# Generated by Django 4.0 on 2021-12-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0009_alter_exhibit_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='response', to='studios.comment'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='images',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='gallery', to='studios.image'),
        ),
    ]
