# Generated by Django 4.0 on 2021-12-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0010_alter_exhibit_comments_alter_exhibit_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
